<h1>Carga de la Pila</h1>

<div class="progress">
    <div id="carga" class="progress-bar progress-bar-striped progress-bar-animated bg-warning" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 20%"></div>
</div>

<script type="text/javascript">
    function get_status() {
        var url = 'https://kumbia.herokuapp.com/pila';
        axios.get(url)
            .then(function(response) {
                var pila=(response.data.pila[0].carga);
                let porcentaje=pila*100/1.6;     
        
                var carga = document.getElementById("carga");
                var resp = "width:" + porcentaje + "%";
                carga.setAttribute("style", resp);
                setTimeout(function() {
                    get_status();
                }, 300);
            })
    }
    get_status();
</script>